name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project
        run: echo "Project Build Successful"

  report-build-status:

    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Report Build Status
        run: echo "Build Report: SUCCESS"

  deploy:

    needs: report-build-status
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Project
        run: echo "Deployment Started"

  report-deploy-status:

    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Report Deploy Status
        run: echo "Deployment Report: SUCCESS"
